version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://db:27017/pet_shelter
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
